name: build-test-lint
on: [push]
jobs:
  main-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 15
      - run: npm install -g dotenv-cli
      - run: npm install
      - run: npm run build
      - run: npm run test-ci
      - run: npm run lint


